### ISSUE TITLE
Local deploy always gives error 500: TypeError: Item in "from list'' not a string

### ISSUE THREAD

**Issue by hottwaj** [jupyter-incubator/dashboards_bundlers#26] opened 2016-04-08 11:09 UTC
Hi, I'm testing this out on my machine and I'm able to design and view my dashboard (works great!), but when I try to deploy on my local jupyter server I always get a 500 error and the trace back below.

Could this be a problem with my setup or a bug?  If you need any more information let me know.

Cheers

```
[E 11:43:04.009 NotebookApp] Uncaught exception GET /api/bundlers/dashboards_local_deploy?notebook=test.ipynb (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/bundlers/dashboards_local_deploy?notebook=test.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/notebooks/test.ipynb', 'Cookie': 'csrftoken=fCcPnU18RXX4eAY3svO6SwQDQWCEgIrW; __utma=111872281.254605274.1456251227.1459251152.1459339274.28; __utmc=111872281; __utmz=111872281.1456251227.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/hottwaj/venv/lib/python2.7/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/hottwaj/venv/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/hottwaj/venv/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/home/hottwaj/venv/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/hottwaj/venv/lib/python2.7/site-packages/jupyter_cms/bundler.py", line 229, in get
        bundler_mod = import_item(bundler['module_name'])
      File "/home/hottwaj/venv/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
        module = __import__(package, fromlist=[obj])
    TypeError: Item in ``from list'' not a string
[E 11:43:04.011 NotebookApp] {
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate, sdch", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/test.ipynb", 
      "Cookie": "csrftoken=fCcPnU18RXX4eAY3svO6SwQDQWCEgIrW; __utma=111872281.254605274.1456251227.1459251152.1459339274.28; __utmc=111872281; __utmz=111872281.1456251227.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 11:43:04.011 NotebookApp] 500 GET /api/bundlers/dashboards_local_deploy?notebook=test.ipynb (127.0.0.1) 2.72ms referer=http://localhost:8888/notebooks/test.ipynb

```

**Comment by parente** [comment] 2016-04-12 02:49
If you remember the steps you used to install the extension, can you paste them here? It kinda-sorta looks like the notebook configuration file was somehow written incorrectly and so the module reference is broken.

**Comment by hottwaj** [comment] 2016-04-14 16:32
Hey, I can't remember the steps I followed I'm afraid, so I set up a new virtualenv and tested again from scratch but I still get the same error.  

I noticed that the "jupyter dashboards install" command writes settings to a file that is shared across different virtual envs... should I even be using a virtual env for this or was it not intended to be used that way?

Anyway I ran the following to set up the venv:

```
(venv_dashboards)hottwaj@Mint ~/test $ pip install jupyter ipython jupyter_dashboards_bundlers jupyter_dashboards
.......

(venv_dashboards)hottwaj@Mint ~/test $ jupyter dashboards install --user --symlink --overwrite
[ExtensionInstallApp] WARNING | Unrecognized JSON config file version, assuming version 1
[ExtensionInstallApp] Installing jupyter_dashboards JS notebook extensions
removing /home/hottwaj/.local/share/jupyter/nbextensions/jupyter_dashboards
symlink /home/hottwaj/.local/share/jupyter/nbextensions/jupyter_dashboards -> /home/hottwaj/test/venv_dashboards/lib/python2.7/site-packages/jupyter_dashboards/nbextension
[ExtensionInstallApp] Done.
(venv_dashboards)hottwaj@Mint ~/test $ jupyter dashboards activate
[ExtensionActivateApp] WARNING | Unrecognized JSON config file version, assuming version 1
[ExtensionActivateApp] Activating jupyter_dashboards JS notebook extensions
[ExtensionActivateApp] Done.
(venv_dashboards)hottwaj@Mint ~/test $ jupyter dashboards_bundlers activate
[ExtensionActivateApp] WARNING | Unrecognized JSON config file version, assuming version 1
[ExtensionActivateApp] Activating jupyter_dashboards_bundlers JS notebook extensions
[ExtensionActivateApp] Done.
(venv_dashboards)hottwaj@Mint ~/test $ jupyter notebook
```

**Comment by parente** [comment] 2016-04-14 16:34
Thanks. We'll try to take a look at reproducing it. I'm wondering if we have a Python 2 incompatibility.

> should I even be using a virtual env for this or was it not intended to be used that way?

You can use an venv and take off the --user param to install to it instead of your user home dir. Notebook 4.2 (due out soon) will improve ext management from the CLI.

**Comment by hottwaj** [comment] 2016-04-14 16:39
Cool, thanks for the tip on the --user param.  If I there's anything else I can try out let me know!

**Comment by parente** [comment] 2016-04-18 13:24
It's a Python 2 incompat problem and it's in jupyter-incubator/contentmanagement, the underlying extension used here. I hit it while testing https://github.com/jupyter-incubator/contentmanagement/pull/37.

I'll leave this defect open here until the 0.5.0 release of that extension is out fixing the problem. (Today/tomorrow most likely.)

**Comment by parente** [comment] 2016-04-18 14:21
Fixed in contentmanagement master by https://github.com/jupyter-incubator/contentmanagement/pull/37.

Thanks again @hottwaj for reporting.

**Closed by parente** 2016-04-18 14:21 UTC
Labels: bug
